name: kawaii
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - torchtext
  - pytorch-lightning
  - fastapi
  - uvicorn
  - pip:
      - torchmetrics